titleWeb : "Happy Birthday " ,
introTitle : 'Huyền Khứ Trần'  ,
introDesc : Trời hôm nay đẹp quá , phải chăng là vì có chị. Chị yêu , sinh nhật vui vẻ , mong chị mãi tươi cười , đừng để thế giới thiếu mất nụ cười đáng yêu đó nhá` ,
btnIntro : '(• ‿ •)Yêu chị(• ‿ •) ' ,
title : 'Đồng chí có muốn sang năm đón sinh nhật với tôi nữa không ◔◡◔' ,
desc : 'Đồng chí có muốn tết năm sau mở sòng xuyên đêm 30 với tôi không' ,
btn Có : 'Yé :v)))' ,
btnNo : 'Nỏ :v' ,
question : '2025 muốn tôi thua kèo không :v' ,
btnReply : 'Gửi cho diu 3000 trái tim <3' ,
reply : 'Nỏ :v' ,
mess : 'Mình biết mà 🥰. Yêu bạn nhiều :vvv ' ,
messDesc : 'Tối nay 7h, mình chơi game ha. " ,
btn Chấp nhận : 'uci :v))))' ,
messLink : 'https://www.messenger.com/t/4394602963964120' }
